# Generated by Django 4.1.3 on 2022-11-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.DecimalField(decimal_places=23, max_digits=30)),
                ('delta', models.DecimalField(decimal_places=23, max_digits=30)),
                ('u', models.DecimalField(decimal_places=23, max_digits=30)),
                ('g', models.DecimalField(decimal_places=23, max_digits=30)),
                ('r', models.DecimalField(decimal_places=23, max_digits=30)),
                ('i', models.DecimalField(decimal_places=23, max_digits=30)),
                ('z', models.DecimalField(decimal_places=23, max_digits=30)),
                ('redshift', models.DecimalField(decimal_places=23, max_digits=30)),
                ('fecha_creacion', models.DateField()),
                ('galaxy', models.DecimalField(decimal_places=3, max_digits=4)),
                ('qso', models.DecimalField(decimal_places=3, max_digits=4)),
                ('star', models.DecimalField(decimal_places=3, max_digits=4)),
                ('valor_real', models.CharField()),
                ('fecha_actualizacion', models.DateField()),
            ],
        ),
    ]
